feedjack/urls.py
# -*- coding: utf-8 -*-

"""
feedjack
Gustavo Picón
urls.py
"""

from django.conf.urls import patterns, url
from django.views.generic.base import RedirectView

from feedjack import views
from feedjack import newviews, forms

urlpatterns = patterns('',
    url(r'^rss20.xml$', RedirectView.as_view(url='/feed/rss/')),
    url(r'^feed/$', RedirectView.as_view(url='/feed/atom/')),
    url(r'^feed/rss/$', views.rssfeed, name="feed-rss"),
    url(r'^feed/atom/$', views.atomfeed),

    url(r'^feed/subscription/(?P<subscription>\d+)/tag/(?P<tag>.*)/$', RedirectView.as_view(url='/feed/atom/subscription/%(subscription)s/tag/%(tag)s/')),
    url(r'^feed/subscription/(?P<subscription>\d+)/$', RedirectView.as_view(url='/feed/atom/subscription/%(subscription)s/')),
    url(r'^feed/tag/(?P<tag>.*)/$', RedirectView.as_view(url='/feed/atom/tag/%(tag)s/')),

    url(r'^feed/atom/subscription/(?P<subscription>\d+)/tag/(?P<tag>.*)/$', views.atomfeed),
    url(r'^feed/atom/subscription/(?P<subscription>\d+)/$', views.atomfeed),
    url(r'^feed/atom/tag/(?P<tag>.*)/$', views.atomfeed),
    url(r'^feed/rss/subscription/(?P<subscription>\d+)/tag/(?P<tag>.*)/$', views.rssfeed),
    url(r'^feed/rss/subscription/(?P<subscription>\d+)/$', views.rssfeed),
    url(r'^feed/rss/tag/(?P<tag>.*)/$', views.rssfeed),

    url(r'^settings/feed/new/$', newviews.CreateSubscriber.as_view(), name="settings-feedcreate"),
    url(r'^settings/feed/$', newviews.SubscriberList.as_view(), name="settings-feedlist"),
    url(r'^settings/import/opml/$', newviews.OPMLImport.as_view(form_list = [forms.OPMLUploadForm, forms.OPMLEntrySet]), name="settings-import-opml"),

    url(r'^posts/$', newviews.PostView.as_view(), name="post-all"),

    url(r'^subscription/(?P<subscription>\d+)/tag/(?P<tag>.*)/$', views.mainview),
    url(r'^subscription/(?P<subscription>\d+)/$', views.mainview),
    url(r'^tag/(?P<tag>.*)/$', views.mainview, name="post-tag"),

    url(r'^group/(?P<group>\d+)/$', views.mainview),
    url(r'^since/(?P<newer>([0-9]{4,4}-[0-9]{2,2}-[0-9]{2,2}(| [0-9]{2,2}:[0-9]{2,2})|yesterday|last_week|10daysago|30daysago))(?P<asc>(|/asc))/$', views.mainview),

    url(r'^opml/$', views.opml),
    url(r'^foaf/$', views.foaf),
    url(r'^feedtitle/$', views.feedtitle),
    url(r'^$', views.mainview, name="landing"),

)

#~

feedjack/models.py
# -*- coding: utf-8 -*-
# pylint: disable-msg=W0232, R0903, W0131

"""
feedjack
Gustavo Picón
models.py
"""

from django.db import models
from django.utils.translation import ugettext_lazy as _ 
from django.utils.encoding import smart_unicode

from autoslug import AutoSlugField

from feedjack import fjcache


from django.contrib.auth.models import User


class FeedjackUser(models.Model):
    user = models.OneToOneField(User)
    site = models.ForeignKey('Site')

SITE_ORDERBY_CHOICES = (
    (1, _('Date published.')),
    (2, _('Date the post was first obtained.'))
)

class Link(models.Model):
    name = models.CharField(_('name'), max_length=100, unique=True)
    link = models.URLField(_('link'), max_length=2000)

    class Meta:
        verbose_name = _('link')
        verbose_name_plural = _('links')
        
    class Admin:
        pass

    def __unicode__(self):
        return u'%s (%s)' % (self.name, self.link)



class Site(models.Model):
    name = models.CharField(_('name'), max_length=100)
    url = models.CharField(_('url'),
      max_length=100,
      unique=True,
      help_text=u'%s: %s, %s' % (smart_unicode(_('Example')),
        u'http://www.planetexample.com',
        u'http://www.planetexample.com:8000/foo'))
    title = models.CharField(_('title'), max_length=200)
    description = models.TextField(_('description'))
    welcome = models.TextField(_('welcome'), null=True, blank=True)
    greets = models.TextField(_('greets'), null=True, blank=True)

    default_site = models.BooleanField(_('default site'), default=False)
    posts_per_page = models.IntegerField(_('posts per page'), default=20)
    order_posts_by = models.IntegerField(_('order posts by'), default=1,
        choices=SITE_ORDERBY_CHOICES)
    tagcloud_levels = models.IntegerField(_('tagcloud level'), default=5)
    show_tagcloud = models.BooleanField(_('show tagcloud'), default=True)
    
    use_internal_cache = models.BooleanField(_('use internal cache'), default=True)
    cache_duration = models.IntegerField(_('cache duration'), default=60*60*24,
        help_text=_('Duration in seconds of the cached pages and data.') )

    links = models.ManyToManyField(Link, verbose_name=_('links'),
      null=True, blank=True)
    template = models.CharField(_('template'), max_length=100, null=True,
      blank=True, 
      help_text=_('This template must be a directory in your feedjack '
        'templates directory. Leave blank to use the default template.') )

    class Meta:
        verbose_name = _('site')
        verbose_name_plural = _('sites')
        ordering = ('name',)

    def __unicode__(self):
        return self.name

    def save(self):
        if not self.template:
            self.template = 'default'
        # there must be only ONE default site
        defs = Site.objects.filter(default_site=True)
        if not defs:
            self.default_site = True
        elif self.default_site:
            for tdef in defs:
                if tdef.id != self.id:
                    tdef.default_site = False
                    tdef.save()
        self.url = self.url.rstrip('/')
        fjcache.hostcache_set({})
        super(Site, self).save()




class Feed(models.Model):
    feed_url = models.URLField(_('feed url'), unique=True, max_length=255)

    name = models.CharField(_('name'), max_length=100)
    slug = AutoSlugField(populate_from='name', always_update=True)

    @property
    def shortname(self):
        raise DeprecationWarning("Replace Feed.shortname with Feed.slug")
        return self.slug

    is_active = models.BooleanField(_('is active'), default=True,
        help_text=_('If disabled, this feed will not be further updated.') )

    title = models.CharField(_('title'), max_length=200, blank=True)
    tagline = models.TextField(_('tagline'), blank=True)
    link = models.URLField(_('link'), blank=True, max_length=2000)

    # http://feedparser.org/docs/http-etag.html
    etag = models.CharField(_('etag'), max_length=50, blank=True)
    last_modified = models.DateTimeField(_('last modified'), null=True, blank=True)
    last_checked = models.DateTimeField(_('last checked'), null=True, blank=True)

    class Meta:
        verbose_name = _('feed')
        verbose_name_plural = _('feeds')
        ordering = ('name', 'feed_url',)

    def __unicode__(self):
        return u'%s (%s)' % (self.name, self.feed_url)


class Tag(models.Model):
    name = models.CharField(_('name'), max_length=50, unique=True)

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')
        ordering = ('name',)
    
    def __unicode__(self):
        return self.name

    def save(self):
        super(Tag, self).save()

class Post(models.Model):
    feed = models.ForeignKey(Feed, verbose_name=_('feed'), null=False, blank=False)
    title = models.CharField(_('title'), max_length=255)
    link = models.URLField(_('link'), max_length=2000)
    content = models.TextField(_('content'), blank=True)
    date_modified = models.DateTimeField(_('date modified'), null=True, blank=True)
    guid = models.CharField(_('guid'), max_length=200, db_index=True)
    author = models.CharField(_('author'), max_length=50, blank=True)
    author_email = models.EmailField(_('author email'), blank=True)
    comments = models.URLField(_('comments'), blank=True, max_length=2000)
    tags = models.ManyToManyField(Tag, verbose_name=_('tags'))
    date_created = models.DateField(_('date created'), auto_now_add=True)

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')
        ordering = ('-date_modified',)
        unique_together = (('feed', 'guid'),)

    def __unicode__(self):
        return self.title

    def save(self):
        super(Post, self).save()

    def get_absolute_url(self):
        return self.link



class Subscriber(models.Model):
    site = models.ForeignKey(Site, verbose_name=_('site') )
    feed = models.ForeignKey(Feed, verbose_name=_('feed') )
    group = models.ForeignKey('Group', verbose_name=_('group'), null=True, blank=True )

    name = models.CharField(_('name'), max_length=100, null=True, blank=True,
        help_text=_('Keep blank to use the Feed\'s original name.') )
    slug = AutoSlugField(populate_from='name', always_update=True)

    @property
    def shortname(self):
        raise DeprecationWarning("Replace Feed.shortname with Feed.slug")
        return self.slug

    is_active = models.BooleanField(_('is active'), default=True,
        help_text=_('If disabled, this subscriber will not appear in the site or '
        'in the site\'s feed.') )

    class Meta:
        verbose_name = _('subscriber')
        verbose_name_plural = _('subscribers')
        ordering = ('site', 'name', 'feed')
        unique_together = (('site', 'feed'),)

    def __unicode__(self):
        return u'%s in %s' %\
            (unicode(self.feed), unicode(self.site))

    def get_cloud(self):
        from feedjack import fjcloud
        return fjcloud.getcloud(self.site, self.feed.id)

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.feed.name
        super(Subscriber, self).save(*args, **kwargs)

class Group(models.Model):
    name=models.CharField(_('name'), max_length=100)
    parent=models.ForeignKey('Group', verbose_name=_('parent group'), blank=True, null=True)
    def __unicode__(self):
        return u'Group: "%s"'%self.name


#~

feedjack/templates/base.html
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load i18n static %}
{% load url from future %}
<html>
<!--
  Feedjack LostWoods theme
  Simple and green (where's the brown? -brown doesn't count)
 
  Copyright Diego Escalante Urrelo <diegoe@gnome.org>
 -->
<head>
	<meta name="description" content="Feedjack" />
	<meta name="generator" content="Feedjack">
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8">
	<link rel="stylesheet" type="text/css" href="{% static "feedjack/default/style.css" %}" />
        <link rel="alternate" type="application/rss+xml" title="RSS 2.0" href="{% url "feed-rss" %}" />
        {% block extrastyle %}{% endblock %}
        {% block extrahead %}{% endblock %}
        <title>{% block title %}{{ site.title }}{% endblock %}</title>
        {% block js %}{% endblock %}
</head>

<body>
<div id="head">
    <div id="logo">
        <h1><a href="{% url "landing" %}">{{ site.name }}</a></h1>
          {% blocktrans %}A <a href="http://www.feedjack.org/" class="love_feedjack" title="Feedjack Powered">Feedjack</a> Planet powered web based Feedreader{% endblocktrans %}
    </div>
</div>
<div id="content">
    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        <p>{{ message|linebreaks }}</p>
    </li>   
        {% endfor %}
    </ul>   
    <!--<script>
        jQuery("ul.messages li").hide();
        jQuery("ul.messages").children("li").each(function(i, e){
            jQuery(e).fadeIn(2000);
        });
    </script>-->
    {% endif %}
    {% block content %}{% endblock %}
</div>
<div id="sidebar">
{% block sidebar %}
    <h4>Meta</h4>
    <div>
    {% block sidebar_meta %}
    {% trans "Last update" %}: <br/><b>{{ last_modified|date:"l, d. F Y, G:i:s" }}</b>
    {% comment %}TODO: num feeds, num posts, maybe num users{% endcomment %}
    {% endblock%}
    </div>
    <h4>Profile</h4>
    <div>
    {% block sidebar_profile %}
    {% if user.is_authenticated %}
        {% blocktrans %}You are logged in as <b>{{ user }}</b>{% endblocktrans %}<br />
        <ul>
        </ul>
    {% else %}
        {% url "django.contrib.auth.views.login" as loginurl %}
        {% blocktrans %}
        <a href="{{ loginurl }}?next=/">login</a>
        {% endblocktrans %}
    {% endif %}
    {% endblock %}
    </div>
    <h4>{% trans "People" %}</h4>
    <div>
    {% block sidebar_subscribers %}
        {% for group in subscriber_groups %}
        {% if group.subscriber_set %}
        <fieldset class="group">
            <legend class="groupname"><a href="/group/{{group.id}}/">{{group.name}}</a></legend>
        {% for feed in group.subscriber_set.all %}
        <span><a class="nombre" href="/subscription/{{ feed.feed.id }}" title="{{ feed.feed.title }}">{{ feed.name }}</a> (<a href="{{ feed.feed.link }}">{% trans "website" %}</a>, <a href="{{ feed.feed.feed_url }}" {% if feed.feed.last_modified %}title="{% blocktrans with feed.feed.last_modified as last_modified %}feed (last modified: {{ last_modified }}){% endblocktrans %}"{% else %}title="{% trans "feed" %}"{% endif %}>{% trans "feed" %}</a>)</span>&nbsp;&nbsp;&nbsp;<!-- FIXME -->
        {% endfor %}
        </fieldset>
        {% endif %}
        {% endfor %}
    {% endblock%}
    </div>
    <h4>{% trans "Only new Posts" %}</h4>
    <div>
    {% block sidebar_postssince %}
        <fieldset class="group">
            <legend class="groupname">posts since</legend>
            <a href="/since/yesterday/">yesterday</a>
            <a href="/since/yesterday/asc/">(older posts first)</a>
            &nbsp;&nbsp;
            <a href="/since/last_week/">last week</a>
            <a href="/since/last_week/asc/">(older posts first)</a>
            &nbsp;&nbsp;
            <a href="/since/10daysago/">10 days ago</a>
            <a href="/since/10daysago/asc/">(older posts first)</a>
            &nbsp;&nbsp;
            <a href="/since/30daysago/">30 days ago</a>
            <a href="/since/30daysago/asc/">(older posts first)</a>
            {% if now %}
            &nbsp;&nbsp;
            <a href="/since/{{now}}/" title="open this now and refresh it later to see which posts are new">NOW</a>
            <a href="/since/{{now}}/asc/">(older posts first)</a>
            {% endif %}
        </fieldset>
    {% endblock%}
    </div>
{% endblock %}
</div>
</body>
</html>

feedjack/templates/pagination.html
{% load i18n %}
<div id="paginate">
{% if has_previous %}
<div class="pageitem"><a href="?page={{ previous }}">&lt;&lt;</a></div>
{% endif %}
<div class="pageitem">
  Page {{ page }} of {{ pages }} ({% blocktrans count hits as posts %}{{ posts }} post{% plural %}{{ posts }} posts{% endblocktrans %})
</div>
{% if subscription %}
<div class="pageitem username"><a href="{{ subscription.feed.link }}">{{ subscription.name }}</a></div>
{% endif %}
{% if tag %}
<div class="pageitem tagname">{{ tag.name }}</div>
{% endif %}
{% if has_next %}
<div class="pageitem"><a href="?page={{ next }}">&gt;&gt;</a></div>
{% endif %}
</div>